export const SHARED_EVENTS = [
  {
    id: 'EVT-2026-001',
    eventName: 'Sophia & James Wedding & Reception',
    couple: 'Sophia & James Sterling',
    clientName: 'Sophia & James Sterling',
    eventType: 'Wedding & Reception',
    date: '2026-08-12',
    startDate: '2026-08-12',
    endDate: '2026-08-13',
    time: '08:00 AM - 11:00 PM',
    startTime: '08:00 AM',
    endTime: '11:00 PM',
    venue: 'The Grand Chateau, Napa Valley',
    package: 'Royal Cinematic 4K',
    amount: '₹8,50,000',
    crew: ['Alex V. (Lead)', 'Marco K. (Drone)', 'Maya S. (2nd)'],
    payment: 'Paid in Full',
    paymentSeverity: 'success',
    status: 'Shooting Today',
    statusSeverity: 'danger',
    progress: 10,
    notes: '2-Day multi-day wedding and evening reception gala.'
  },
  {
    id: 'EVT-2026-002',
    eventName: 'Priya & Rohan Sangeet & Mehendi',
    couple: 'Priya & Rohan Sharma',
    clientName: 'Priya & Rohan Sharma',
    eventType: 'Sangeet & Mehendi',
    date: '2026-08-15',
    startDate: '2026-08-15',
    endDate: '2026-08-15',
    time: '04:00 PM - 01:00 AM',
    startTime: '04:00 PM',
    endTime: '01:00 AM',
    venue: 'The Ritz Carlton Ballroom, Mumbai',
    package: 'Heritage Multi-Day Gold',
    amount: '₹6,20,000',
    crew: ['Elena R. (Lead)', 'David P. (Video)'],
    payment: 'Deposit Paid (50%)',
    paymentSeverity: 'info',
    status: 'Confirmed',
    statusSeverity: 'info',
    progress: 20,
    notes: 'Traditional choreography coverage & LED backdrop lighting.'
  },
  {
    id: 'EVT-2026-003',
    eventName: 'Olivia & Liam Destination Wedding',
    couple: 'Olivia & Liam Vance',
    clientName: 'Olivia & Liam Vance',
    eventType: 'Destination Wedding',
    date: '2026-08-04',
    startDate: '2026-08-04',
    endDate: '2026-08-06',
    time: '10:00 AM - 10:00 PM',
    startTime: '10:00 AM',
    endTime: '10:00 PM',
    venue: 'Sunset Cove Resort, Miami',
    package: 'Destination Luxe Film',
    amount: '₹12,00,000',
    crew: ['Alex V. (Lead)', 'Sarah L. (Colorist)'],
    payment: 'Paid in Full',
    paymentSeverity: 'success',
    status: 'In Post-Production',
    statusSeverity: 'warning',
    progress: 75,
    notes: 'Beachside sunset ceremony.'
  },
  {
    id: 'EVT-2026-004',
    eventName: 'Emma & Benjamin Sunset Pre-Wedding',
    couple: 'Emma & Benjamin Hayes',
    clientName: 'Emma & Benjamin Hayes',
    eventType: 'Pre-Wedding Shoot',
    date: '2026-07-28',
    startDate: '2026-07-28',
    endDate: '2026-07-28',
    time: '06:00 AM - 02:00 PM',
    startTime: '06:00 AM',
    endTime: '02:00 PM',
    venue: 'Royal Botanical Gardens',
    package: 'Classic Memories',
    amount: '₹3,50,000',
    crew: ['Maya S. (Lead)'],
    payment: 'Paid in Full',
    paymentSeverity: 'success',
    status: 'Delivered',
    statusSeverity: 'success',
    progress: 100,
    notes: 'High resolution digital drive delivered.'
  },
  {
    id: 'EVT-2026-005',
    eventName: 'Chloe & Nathaniel Gala Dinner',
    couple: 'Chloe & Nathaniel Dupont',
    clientName: 'Chloe & Nathaniel Dupont',
    eventType: 'Gala Dinner & Cocktail',
    date: '2026-08-22',
    startDate: '2026-08-22',
    endDate: '2026-08-22',
    time: '06:00 PM - 12:00 AM',
    startTime: '06:00 PM',
    endTime: '12:00 AM',
    venue: 'Belmond Villa San Michele',
    package: 'Signature Cinema + Album',
    amount: '₹5,80,000',
    crew: ['Elena R. (Lead)', 'Marco K. (Drone)'],
    payment: 'Deposit Due',
    paymentSeverity: 'danger',
    status: 'Pending Deposit',
    statusSeverity: 'danger',
    progress: 0,
    notes: 'Awaiting deposit payment.'
  },
  {
    id: 'EVT-2026-006',
    eventName: 'Aarav & Ananya Royal Wedding',
    couple: 'Aarav & Ananya Mehta',
    clientName: 'Aarav & Ananya Mehta',
    eventType: 'Haldi & Wedding Ceremony',
    date: '2026-08-18',
    startDate: '2026-08-18',
    endDate: '2026-08-20',
    time: '07:00 AM - 09:00 PM',
    startTime: '07:00 AM',
    endTime: '09:00 PM',
    venue: 'Umaid Bhawan Palace, Jodhpur',
    package: 'Royal Cinematic 4K',
    amount: '₹14,50,000',
    crew: ['Alex V. (Lead)', 'David P. (Video)', 'Marco K. (Drone)'],
    payment: 'Deposit Paid (60%)',
    paymentSeverity: 'info',
    status: 'Confirmed',
    statusSeverity: 'info',
    progress: 30,
    notes: '3-Day grand royal destination wedding.'
  },
  {
    id: 'EVT-2026-007',
    eventName: 'Rahul & Anu Engagement',
    couple: 'Rahul & Anu Verma',
    clientName: 'Rahul & Anu Verma',
    eventType: 'Engagement & Couple Portraits',
    date: '2026-08-18',
    startDate: '2026-08-18',
    endDate: '2026-08-18',
    time: '02:00 PM - 07:00 PM',
    startTime: '02:00 PM',
    endTime: '07:00 PM',
    venue: 'Leela Palace Ballroom, Bengaluru',
    package: 'Classic Memories',
    amount: '₹4,00,000',
    crew: ['Maya S. (Lead)'],
    payment: 'Paid in Full',
    paymentSeverity: 'success',
    status: 'Confirmed',
    statusSeverity: 'info',
    progress: 15,
    notes: 'Ring ceremony & indoor hall portraits.'
  },
  {
    id: 'EVT-2026-008',
    eventName: 'Karthik & Divya Pre-Wedding',
    couple: 'Karthik & Divya',
    clientName: 'Karthik & Divya',
    eventType: 'Pre-Wedding Shoot',
    date: '2026-08-18',
    startDate: '2026-08-18',
    endDate: '2026-08-18',
    time: '05:00 PM - 09:00 PM',
    startTime: '05:00 PM',
    endTime: '09:00 PM',
    venue: 'Nandi Hills Sunrise Point',
    package: 'Cinematic Pre-Wedding',
    amount: '₹1,50,000',
    crew: ['David P. (Video)'],
    payment: 'Paid in Full',
    paymentSeverity: 'success',
    status: 'Confirmed',
    statusSeverity: 'info',
    progress: 10,
    notes: 'Outdoor drone & golden hour shoot.'
  },
  {
    id: 'EVT-2026-009',
    eventName: 'Vikram & Ananya Reception',
    couple: 'Vikram & Ananya',
    clientName: 'Vikram & Ananya',
    eventType: 'Reception',
    date: '2026-08-18',
    startDate: '2026-08-18',
    endDate: '2026-08-18',
    time: '07:00 PM - 11:30 PM',
    startTime: '07:00 PM',
    endTime: '11:30 PM',
    venue: 'Taj West End, Bengaluru',
    package: 'Royal Cinematic 4K',
    amount: '₹3,80,000',
    crew: ['Karthik K. (Photographer)'],
    payment: 'Deposit Paid (50%)',
    paymentSeverity: 'info',
    status: 'Confirmed',
    statusSeverity: 'info',
    progress: 5,
    notes: 'Evening reception party.'
  }
]
